name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Installed modules
      run: npm install
    - name: run tests
      run: npm run test:unit 